// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMZupWjoYbelCubQ8JH8HqVW1IIigBQPs',
    appId: '1:153888942856:android:53f886f1bfa26d5a385abd',
    messagingSenderId: '153888942856',
    projectId: 'arproject-aa391',
    storageBucket: 'arproject-aa391.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsWIP9_8mRUYr59CWavgWqKV9DXiQCs8c',
    appId: '1:153888942856:web:b3ae69a38a5682d4385abd',
    messagingSenderId: '153888942856',
    projectId: 'arproject-aa391',
    authDomain: 'arproject-aa391.firebaseapp.com',
    storageBucket: 'arproject-aa391.firebasestorage.app',
    measurementId: 'G-LTH8M8XN28',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpLRwEmh7rcLgjITKXI3DDiFm0NiqLU1Y',
    appId: '1:153888942856:ios:9a76c9a482eb67e1385abd',
    messagingSenderId: '153888942856',
    projectId: 'arproject-aa391',
    storageBucket: 'arproject-aa391.firebasestorage.app',
    iosBundleId: 'com.punitayare.arcore',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpLRwEmh7rcLgjITKXI3DDiFm0NiqLU1Y',
    appId: '1:153888942856:ios:9a76c9a482eb67e1385abd',
    messagingSenderId: '153888942856',
    projectId: 'arproject-aa391',
    storageBucket: 'arproject-aa391.firebasestorage.app',
    iosBundleId: 'com.punitayare.arcore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsWIP9_8mRUYr59CWavgWqKV9DXiQCs8c',
    appId: '1:153888942856:web:75cad5ae91a9eb24385abd',
    messagingSenderId: '153888942856',
    projectId: 'arproject-aa391',
    authDomain: 'arproject-aa391.firebaseapp.com',
    storageBucket: 'arproject-aa391.firebasestorage.app',
    measurementId: 'G-WBGTQJ4KZN',
  );

}